import re
import yaml
from langchain_core.messages import HumanMessage
from llm_provider import get_llm


def extract_yaml(text: str) -> str:
    text = text.strip()

    text = re.sub(r"```yaml", "", text, flags=re.IGNORECASE)
    text = re.sub(r"```", "", text)

    return text.strip()


def generate_yaml_with_llm(
    user_request: str,
    app_name: str,
    image: str,
    replicas: int,
    port: int,
    service_type: str,
    llm_model: str,
):
    llm = get_llm(llm_model)

    prompt = f"""
You are a Kubernetes YAML generator.

Return ONLY raw Kubernetes YAML.
Do not explain anything.
Do not use markdown.
Do not use Helm.
Do not use placeholders.
Do not use variables.
Do not use {{ }} syntax.
The output must be directly valid for kubectl apply.

User request:
{user_request}

Concrete values to use:
app_name: {app_name}
image: {image}
replicas: {replicas}
port: {port}
service_type: {service_type}

Generate exactly two Kubernetes resources:
1. Deployment
2. Service

Deployment requirements:
- apiVersion: apps/v1
- kind: Deployment
- metadata.name: {app_name}-deployment
- spec.replicas: {replicas}
- selector.matchLabels.app: {app_name}
- template.metadata.labels.app: {app_name}
- one container
- container name: {app_name}
- container image: {image}
- containerPort: {port}
- Container ports must be written as:
  ports:
  - containerPort: <port>
- Never write containerPort directly under the container.

Service requirements:
- apiVersion: v1
- kind: Service
- metadata.name: {app_name}-service
- selector.app: {app_name}
- port: {port}
- targetPort: {port}
- type: {service_type}

Correct container example:

containers:
- name: nginx
  image: nginx
  ports:
  - containerPort: 80

Incorrect example:

containers:
- name: nginx
  image: nginx
  containerPort: 80

Use YAML document separator --- between resources.
"""

    response = llm.invoke([HumanMessage(content=prompt)])
    yaml_text = extract_yaml(response.content)

    try:
        list(yaml.safe_load_all(yaml_text))
        docs = list(yaml.safe_load_all(yaml_text))

        deployment = docs[0]

        containers = deployment["spec"]["template"]["spec"]["containers"]

        if "ports" not in containers[0]:
            print("[LLM YAML VALIDATOR] Missing ports in container")
            return False, yaml_text, "Deployment missing container ports section"
    except Exception as e:
        return False, yaml_text, f"Invalid YAML generated: {e}"
    
    

    return True, yaml_text, "YAML generated by LLM"