import re
import yaml

from langchain_core.messages import HumanMessage
from llm.llm_provider import get_llm


def extract_yaml(text: str) -> str:
    text = text.strip()
    text = re.sub(r"```yaml", "", text, flags=re.IGNORECASE)
    text = re.sub(r"```", "", text)
    return text.strip()


def validate_llm_yaml(
    yaml_text: str,
    app_name: str,
    image: str,
    replicas: int,
    port: int,
    service_type: str,
):
    try:
        docs = list(yaml.safe_load_all(yaml_text))
    except Exception as e:
        return False, f"Invalid YAML syntax: {e}"

    docs = [doc for doc in docs if doc is not None]

    if len(docs) != 2:
        return False, "YAML must contain exactly two documents: Deployment and Service"

    kinds = [doc.get("kind") for doc in docs]

    if "Deployment" not in kinds:
        return False, "YAML must contain a Deployment"

    if "Service" not in kinds:
        return False, "YAML must contain a Service"

    deployment = next(doc for doc in docs if doc.get("kind") == "Deployment")
    service = next(doc for doc in docs if doc.get("kind") == "Service")

    if deployment.get("metadata", {}).get("name") != f"{app_name}-deployment":
        return False, "Deployment name does not match expected app_name"

    if service.get("metadata", {}).get("name") != f"{app_name}-service":
        return False, "Service name does not match expected app_name"

    deployment_labels = (
        deployment.get("spec", {})
        .get("template", {})
        .get("metadata", {})
        .get("labels", {})
    )

    selector_labels = (
        deployment.get("spec", {})
        .get("selector", {})
        .get("matchLabels", {})
    )

    service_selector = service.get("spec", {}).get("selector", {})

    if deployment_labels.get("app") != app_name:
        return False, "Deployment pod label app does not match app_name"

    if selector_labels.get("app") != app_name:
        return False, "Deployment selector app does not match app_name"

    if service_selector.get("app") != app_name:
        return False, "Service selector app does not match app_name"

    containers = (
        deployment.get("spec", {})
        .get("template", {})
        .get("spec", {})
        .get("containers", [])
    )

    if len(containers) != 1:
        return False, "Deployment must contain exactly one container"

    container = containers[0]

    if container.get("image") != image:
        return False, "Container image does not match requested image"

    if "ports" not in container:
        return False, "Deployment missing container ports section"

    if container["ports"][0].get("containerPort") != port:
        return False, "Container port does not match requested port"

    if deployment.get("spec", {}).get("replicas") != replicas:
        return False, "Deployment replicas do not match requested replicas"

    if service.get("spec", {}).get("type") != service_type:
        return False, "Service type does not match requested service_type"

    service_ports = service.get("spec", {}).get("ports", [])

    if not service_ports:
        return False, "Service must contain ports"

    if service_ports[0].get("port") != port:
        return False, "Service port does not match requested port"

    if service_ports[0].get("targetPort") != port:
        return False, "Service targetPort does not match requested port"

    return True, "YAML generated by LLM"


def generate_yaml_with_llm(
    user_request: str,
    app_name: str,
    image: str,
    replicas: int,
    port: int,
    service_type: str,
    llm_model: str,
):
    llm = get_llm(llm_model)

    prompt = f"""
You are a Kubernetes YAML generator.

Return ONLY raw Kubernetes YAML.
Do not explain anything.
Do not use markdown.
Do not use Helm.
Do not use placeholders.
Do not use variables.
Do not use {{{{ }}}} syntax.
The output must be directly valid for kubectl apply.

User request:
{user_request}

Concrete values to use:
app_name: {app_name}
image: {image}
replicas: {replicas}
port: {port}
service_type: {service_type}

Generate exactly two Kubernetes resources:
1. Deployment
2. Service

Deployment requirements:
- apiVersion: apps/v1
- kind: Deployment
- metadata.name: {app_name}-deployment
- spec.replicas: {replicas}
- selector.matchLabels.app: {app_name}
- template.metadata.labels.app: {app_name}
- one container
- container name: {app_name}
- container image: {image}
- containerPort: {port}
- Container ports must be written as:
  ports:
  - containerPort: {port}
- Never write containerPort directly under the container.

Service requirements:
- apiVersion: v1
- kind: Service
- metadata.name: {app_name}-service
- selector.app: {app_name}
- port: {port}
- targetPort: {port}
- type: {service_type}

Use YAML document separator --- between resources.
"""

    response = llm.invoke([HumanMessage(content=prompt)])
    yaml_text = extract_yaml(response.content)

    is_valid, message = validate_llm_yaml(
        yaml_text=yaml_text,
        app_name=app_name,
        image=image,
        replicas=replicas,
        port=port,
        service_type=service_type,
    )

    if not is_valid:
        print(f"[LLM YAML VALIDATOR] {message}")
        return False, yaml_text, message

    return True, yaml_text, message