"""
Genera scripts de instalación de Kubernetes.

Incluye:
- Setup del master
- Setup de workers
- Configuración de containerd y kubeadm

Scripts seguros y deterministas.
"""


def generate_cluster_plan(params: dict):
    masters = params["masters"]
    workers = params["workers"]
    cni = params["cni"]
    version = params["kubernetes_version"]
    runtime = params["container_runtime"]

    return f"""
Plan para desplegar un clúster Kubernetes desde cero:

1. Preparar infraestructura base:
   - {masters} nodo(s) master/control-plane
   - {workers} nodo(s) worker
   - Máquinas Linux Ubuntu ya provisionadas por el cloud system
   - Conectividad y SSH funcionales entre nodos

2. Instalar dependencias en todos los nodos:
   - {runtime}
   - kubeadm
   - kubelet
   - kubectl
   - versión Kubernetes: {version}

3. Inicializar el nodo master:
   - ejecutar kubeadm init
   - configurar kubeconfig
   - instalar plugin CNI: {cni}

4. Unir los workers:
   - ejecutar kubeadm join en cada worker usando el token generado por el master

5. Validar el clúster:
   - kubectl get nodes
   - kubectl get pods -A
"""


def generate_master_script(params: dict):
    cni = params["cni"]
    version = params["kubernetes_version"]

    if cni == "flannel":
        cni_command = "kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
        pod_cidr = "10.244.0.0/16"
    else:
        cni_command = "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/calico.yaml"
        pod_cidr = "192.168.0.0/16"

    return f"""#!/bin/bash

set -e

echo "[MASTER] Installing dependencies..."
sudo apt update
sudo apt install -y apt-transport-https ca-certificates curl gpg containerd

echo "[MASTER] Configuring containerd..."
sudo mkdir -p /etc/containerd
containerd config default | sudo tee /etc/containerd/config.toml >/dev/null
sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
sudo systemctl restart containerd
sudo systemctl enable containerd

echo "[MASTER] Disabling swap..."
sudo swapoff -a
sudo sed -i '/ swap / s/^/#/' /etc/fstab

echo "[MASTER] Installing Kubernetes components ({version})..."
sudo mkdir -p -m 755 /etc/apt/keyrings
curl -fsSL https://pkgs.k8s.io/core:/stable:/{version}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{version}/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

sudo apt update
sudo apt install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl

echo "[MASTER] Initializing Kubernetes cluster..."
sudo kubeadm init --pod-network-cidr={pod_cidr}

echo "[MASTER] Configuring kubeconfig..."
mkdir -p $HOME/.kube
sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

echo "[MASTER] Installing CNI: {cni}"
{cni_command}

echo "[MASTER] Join command for workers:"
kubeadm token create --print-join-command
"""


def generate_worker_script(params: dict):
    version = params["kubernetes_version"]

    return f"""#!/bin/bash

set -e

echo "[WORKER] Installing dependencies..."
sudo apt update
sudo apt install -y apt-transport-https ca-certificates curl gpg containerd

echo "[WORKER] Configuring containerd..."
sudo mkdir -p /etc/containerd
containerd config default | sudo tee /etc/containerd/config.toml >/dev/null
sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
sudo systemctl restart containerd
sudo systemctl enable containerd

echo "[WORKER] Disabling swap..."
sudo swapoff -a
sudo sed -i '/ swap / s/^/#/' /etc/fstab

echo "[WORKER] Installing Kubernetes components ({version})..."
sudo mkdir -p -m 755 /etc/apt/keyrings
curl -fsSL https://pkgs.k8s.io/core:/stable:/{version}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{version}/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

sudo apt update
sudo apt install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl

echo "[WORKER] Execute the kubeadm join command generated by the master:"
echo "sudo kubeadm join <MASTER_IP>:6443 --token <TOKEN> --discovery-token-ca-cert-hash sha256:<HASH>"
"""


def generate_virtualbox_script(params: dict):
    workers = params["workers"]
    base_ip = "192.168.56.10"  # IP base para master
    master_ip = base_ip
    worker_ips = [f"192.168.56.{11 + i}" for i in range(workers)]

    worker_clone_commands = ""
    for i in range(workers):
        worker_clone_commands += f"""
VBoxManage clonevm "ubuntu-k8s-template" --name "k8s-worker-{i+1}-auto" --register
VBoxManage modifyvm "k8s-worker-{i+1}-auto" --memory 2048 --cpus 2
VBoxManage modifyvm "k8s-worker-{i+1}-auto" --nic1 nat
VBoxManage modifyvm "k8s-worker-{i+1}-auto" --nic2 hostonly --hostonlyadapter2 "VirtualBox Host-Only Ethernet Adapter"
VBoxManage guestproperty set "k8s-worker-{i+1}-auto" /VirtualBox/GuestInfo/Net/0/V4/IP {worker_ips[i]}
VBoxManage startvm "k8s-worker-{i+1}-auto" --type headless
"""

    return f"""# Auto-generated VirtualBox provisioning script
# This script assumes an existing clean Ubuntu template VM named:
# ubuntu-k8s-template
#
# The template must already have:
# - Ubuntu installed
# - SSH enabled
# - user configured
# - no Kubernetes installed
# - VirtualBox Guest Additions installed for IP assignment

Write-Host "Creating Kubernetes master VM..."
VBoxManage clonevm "ubuntu-k8s-template" --name "k8s-master-auto" --register
VBoxManage modifyvm "k8s-master-auto" --memory 4096 --cpus 2
VBoxManage modifyvm "k8s-master-auto" --nic1 nat
VBoxManage modifyvm "k8s-master-auto" --nic2 hostonly --hostonlyadapter2 "VirtualBox Host-Only Ethernet Adapter"
VBoxManage guestproperty set "k8s-master-auto" /VirtualBox/GuestInfo/Net/0/V4/IP {master_ip}
VBoxManage startvm "k8s-master-auto" --type headless

Write-Host "Creating Kubernetes worker VMs..."
{worker_clone_commands}

Write-Host "VirtualBox VMs created and started."
Write-Host "Waiting 60 seconds for VMs to boot..."
Start-Sleep -Seconds 60
Write-Host "VMs should be ready. IPs assigned: Master={master_ip}, Workers={worker_ips}"
"""


def generate_inventory_json(params: dict):
    workers = params["workers"]
    master_ip = "192.168.56.10"
    worker_ips = [f"192.168.56.{11 + i}" for i in range(workers)]

    workers_list = [{"host": ip} for ip in worker_ips]

    inventory = {
        "ssh_user": "ubuntu",  # Asumiendo usuario ubuntu en las VMs
        "master": {"host": master_ip},
        "workers": workers_list,
    }

    return inventory


def generate_cluster_artifacts(params: dict):
    cluster_plan = generate_cluster_plan(params)
    master_script = generate_master_script(params)
    worker_script = generate_worker_script(params)
    virtualbox_script = ""
    inventory = {}

    return cluster_plan, master_script, worker_script, virtualbox_script, inventory
